### ISSUE TITLE
Markdown Major Mode

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/VSpaceCode#108]
Creating an issue just to track my work. This is spawned from #98. One small question that I have is more of a philosophical one, so pinging @MarcoIeni and @stevenguh.

I'm building out the mapping and would like your thoughts on whether or not I should make additional menus expecting to allow VSpaceCode to eventually build in all mappings available in a theoretically feature-complete Markdown major mode, or should I just do what makes the "most sense" given the commands that are available in Markdown All in One? For example, using [the Markdown layer](https://develop.spacemacs.org/layers/+lang/markdown/README.html) as a basis for implementation, I'd be making the mapping for "bold" `SPC m x b` instead of `SPC m b`. The main benefit of this would be reducing the need to shuffle things around down the line when this menu gets more built-out.

The reason why I ask is because right now, it doesn't seem like there will be a ton of keybindings in the "top layer" (i.e. `SPC m <something>`), despite there not being enough mappings at the start to justify creating whole-new menus. Spacemac's Markdown layer has enough commands to justify the split into several menus, but it doesn't seem like that'll be the case from the get-go for VSpaceCode.

**Comment by stevenguh** [comment]
Since the command offered by the extension for each language is so different from spacemacs, it's going to be difficult to replicate all the key bindings in the spacemacs' layers. I think it's probably good to try our best to map to the best of the commands available. Some submenu like `<spc> m x` could have the same semantic across different major; however, I also don't think it makes sense to have a submenu if it only contains one item.

Try out best and we can always change it, right? ;)

**Comment by macintacos** [comment]
True! I guess we can keep saying that until 1.0 😅

**Comment by MarcoIeni** [comment]
This is a very good question and once we answer it we should document it in the contributing guidelines.

My position is that whenever it makes sense we should preserve spacemacs users muscle memory.
But we can:
- add key bindings to the spacemacs one
- replace spacemacs key bindings if they are not applicable

> I also don't think it makes sense to have a submenu if it only contains one item.

Exactly. One example is that we use `spc ;` instead of `spc ; ;` to comment.

> I should make additional menus expecting to allow VSpaceCode to eventually build in all mappings available in a theoretically feature-complete Markdown major mode, or should I just do what makes the "most sense" given the commands that are available in Markdown All in One?

If you think that one action could be accomplished by another extension in vscode, I think you should leave room for it.

So I agree with you: using `<spc> m x b` for bold is good because it maintains compatibility with spacemacs and leaves room for other key bindings under `<spc> m b`, `<spc> m i` (italic) and so on!
