### ISSUE TITLE
4 keystrokes keybindings

### ISSUE THREAD

**Issue by danielpza** [VSpaceCode/VSpaceCode#11]
Is it possible to have a keybinding consisting of SPC + 3 keystrokes (eg. `SPC x l s`) ?

**Comment by StreakyCobra** [comment]
I actually had troubles with this one, it's why I put it on `SPC x s` for now :see_no_evil:. I didn't had time to troubleshoot if the problem was due to <kbd>l</kbd> being a direction key, hence breaking the combination, or due to the length of the combination itself.

If you find it out please let us know :-)

**Comment by purge** [comment]
I'm not sure when this was fixed in vscode / vim extension but I can now use 4 keystroke keybindings in my configuration whereas before they would not work 🎊

**Comment by StreakyCobra** [comment]
@purge Thanks for the info!

@danielpza Is this answering your question? If yes the issue can probably be closed :)

**Comment by danielpza** [comment]
Yes, it should be closed, however I'm not using vscode anymore so yeah, I'm gonna close the issue. If I use vscode/vspacecode again I'll adjust the keybindings. Thanks.
