### ISSUE TITLE
Document existing keybindings with the command they execute so you can remap them

### ISSUE THREAD

**Issue by danielo515** [VSpaceCode/VSpaceCode#116]
## Problem

When I want to re-assign one of the existing commands to a different key, I have no idea of what command to use. For example, if I want `leader f o` to open a file, I have to go to this extension repository, check the package.json and look for this snippet:

```
{
"key": "f",
"name": "Open file/folder",
"type": "command",
"command": "file-browser.open"
},
```

If I try to check this info on the extension page on the marketplace, this is what I see:

![image](https://user-images.githubusercontent.com/2270425/95321058-c51e1180-089a-11eb-9f37-c328c51021ad.png)

## Solution

Document the command that a default mapping executes along with the mapping (on the docs page)

## Alternatives

Maybe just putting the list of contributions properly formatted on the Extension description?

## Additional context

I want to re-assign some of the existing mappings to others that better suit my needs, but it is very hard to deduce which one the extension is using for each default keybinding, some are native from VSCode, some others are custom.

**Comment by stevenguh** [comment]
Just make sure I understand the request here. You are proposing we put the command we are running for each binding in https://vspacecode.github.io/docs/default-keybindings. (Btw, that doc is generated by https://github.com/VSpaceCode/VSpaceCode/blob/v0.8.2/scripts/keybindings.js)

As far as the alternatives, I don't think we have much control over how's it is displayed on the extension description. We can try move away from having bindings default in the `package.json` so it won't show up as a list of [object Object]. That would be quite a bit of engineering work for little bit of gain because the system is designed to directly use the config and detect changes.

**Comment by danielo515** [comment]
> Just make sure I understand the request here. Are you proposing we put the command we are running for each binding in https://vspacecode.github.io/docs/default-keybindings? (Btw, that doc is generated by https://github.com/VSpaceCode/VSpaceCode/blob/v0.8.2/scripts/keybindings.js)

Yes, exactly. That will make it easy to remap them to whatever key combination suits your needs. It is a bit hard to "explore" VSCode commands, and the ones that are specific of this extension even more, that's why I'm proposing this.

**Comment by stevenguh** [comment]
Updated the script in b4bdc9eb256c6c23aded72f3ee85f81c1c5297a8, and the table on the website will be update on the next deploy

**Comment by danielo515** [comment]
Awesome thanks!
