### ISSUE TITLE
<space> in file selector without editor tabs closes the file selector

### ISSUE THREAD

**Issue by max-sixty** [VSpaceCode/VSpaceCode#119]
Firstly, a massive congrats and thank you for such an awesome extension. It's already one of my favorite.

## Bug description

`<space>` in file selector without editor tabs closes the file selector

## To Reproduce

1. Close all editor tabs
2. Cmd+shift+P for file selector
3. Type a few characters "init"
4. Hit space
5. File selector closes, replaced by vspacecode selector

## Expected behavior

File selector shouldn't close on space, and doesn't with editor tabs open

## Screenshots

(lmk if not repro and I'll make a gif)

## Settings

https://gist.github.com/max-sixty/a6e11de8576124611433e1808940d90f

## System information

CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 3, 3
Memory (System) | 32.00GB (0.26GB free)
Process Argv | -psn_0_110619 --crash-reporter-id e41529c1-a371-4515-8318-d943020d05f5
Screen Reader | no
VM | 0%

**Comment by stevenguh** [comment]
I think this is fixed by https://github.com/VSpaceCode/VSpaceCode/pull/112 and released in [v0.8.1](https://github.com/VSpaceCode/VSpaceCode/blob/master/CHANGELOG.md#081---2020-09-29). This requires reconfiguration of keybindings.json. You can update this [section](https://gist.github.com/max-sixty/a6e11de8576124611433e1808940d90f#file-keybindingsmac-json-L138-L142) of your keybindings.json like in #112, or you can run the command to reconfigure keybindings.

Btw, https://github.com/VSpaceCode/VSpaceCode/issues/105 is the issue to improve the way to tell user to update their keybindings/settings in case of update.

**Comment by max-sixty** [comment]
It is fixed! Thank you!
