### ISSUE TITLE
Key bindings should be alphabetically ordered by default

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#120]
## Problem

Right now key bindings are not alphabetically ordered and it's a little bit confusing to browse the which key menu. 

## Solution

We could enable the setting to alphabetically order key bindings by default (I can't check which one it is right now) or we could order the key bindings manually in the package.json file. 

## Additional context

In spacemacs key bindings are alphabetically ordered.

**Comment by stevenguh** [comment]
The reason to not automatically order keybindings by default is that sometimes it can hurt the readability. For example: `<spc> w H/J/K/L` might be easier to understand if they are group together right next to each other. However, I understand that alphabetically order can be preferred, that's why we have the option to automatically sort all keys. I would like to hear more from the community about this.

**Comment by gnomesoup** [comment]
I vote for alphabetically ordered by default.

**Comment by MarcoIeni** [comment]
Actually hjkl are really near in the alphabet :P
Spacemacs does alphabetical order and they are next to each other:

![image](https://user-images.githubusercontent.com/11428655/95651017-774a1900-0ae7-11eb-8255-f2154eee9514.png)

Anyway, in general I vote to follow spacemacs conventions whenever possible and not extremely inconvenient.

**Comment by stevenguh** [comment]
Make sense, since we are trying emulate the experience in spacemacs. There are a few approaches I am thinking:
- Set "nonNumericFirst" as the default sorting in the config command
- Implement a special sorting in which-key
- Update the `package.json` to be sorted and also gave us more control in the future where special key should be like `<C-d>` (User's binding will be automatically updated and is a breaking change for any one that uses positional overrides)

I am leading toward the lsat because of the flexibility down the line; also, we can also have a consistent guide for contributor telling them the order of the new key bindings. However, it is a bit manual (This is mostly a one-time cost).

**Comment by MarcoIeni** [comment]
I agree with the last one. I opened #121
