### ISSUE TITLE
macOS command does not exist

### ISSUE THREAD

**Issue by xiaoyu-tamu** [VSpaceCode/VSpaceCode#13]
key: [ "leader", "p", "l" ]
"command": "workbench.action.files.openFolder",
                 
This command doesn't exist in MacOS.

**Comment by StreakyCobra** [comment]
> This command doesn't exist in MacOS.

I don't have MacOS to test this, but I trust you. If VSCode does not provide this function on MacOS, this is not a problem we can fix here ¯\\_(ツ)_/¯

Except maybe if you know an alternative VSCode command for opening folders, working on all platform, that we can map on `SPC p l` instead of `workbench.action.files.openFolder`?

**Comment by StreakyCobra** [comment]
It is possible to use ` "when": "isMac"` to differentiate keyboard bindings between platforms, see f4a164a293a6b9a39951f615c46f474be520ea2e. You can propose a PR to change this binding for MacOS if you find one that is working :-)

**Comment by StreakyCobra** [comment]
> It is possible to use ` "when": "isMac"` to differentiate keyboard bindings between platforms, see [f4a164a](https://github.com/VSpaceCode/VSpaceCode/commit/f4a164a293a6b9a39951f615c46f474be520ea2e). You can propose a PR to change this binding for MacOS if you find one that is working :-)

Actually the `when` keyword is not supported for VSCodeVim (see c55255096bad6946aefd5a7095d72df65e46f55e), so there is not solution for the moment.

Regarding the first question, the problem is already stated in the README:

https://github.com/VSpaceCode/VSpaceCode#note-for-mac-users

Nothing more I can do here for now :)
