### ISSUE TITLE
<space><i><s> doesn't open the snippet menu anymore

### ISSUE THREAD

**Issue by dankeyy** [VSpaceCode/VSpaceCode#170]
## Bug description

Pressing `<space><i><s>`  used to show a little menu you could choose a snippet from.
Now it just opens a text box which doesn't really do anything.
Maybe that's just me but I'd still like to know why & how to fix it.

## To Reproduce
`<space><i><s>`

## Expected behavior
A menu listing all snippets to choose from.

## Screenshots
![Screenshot_20210130_174515](https://user-images.githubusercontent.com/74069206/106360841-7bfb3d00-6323-11eb-8d6c-b49946b62940.png)

## settings.json file
https://dpaste.org/Tw0c

**Comment by MarcoIeni** [comment]
We are just calling the "Insert Snippet" VS Code action.
Try to press `Ctrl + Shift + p` or `SPC SPC` and select "Insert Snippet" in order to call the action without using VSpaceCode.
If you have the same behavior of `SPC i s`, than we are doing our job correctly.
If this is the case please close this issue and open it in the VSCode repo.

Anyway..why Have you copied the whole VSpaceCode key bindings into your settings? 🤔
Try to remove `"vspacecode.bindings":`. You should have the key bindings if you have installed the extension.
Checkout [installation instruction](https://vspacecode.github.io/docs/) for more details.

**Comment by dankeyy** [comment]
> We are just calling the "Insert Snippet" VS Code action.
> Try to press `Ctrl + Shift + p` or `SPC SPC` and select "Insert Snippet" in order to call the action without using VSpaceCode.
> If you have the same behavior of `SPC i s`, than we are doing our job correctly.
> If this is the case please close this issue and open it in the VSCode repo.
> 
> Anyway..why Have you copied the whole VSpaceCode key bindings into your settings? thinking
> Try to remove `"vspacecode.bindings":`. You should have the key bindings if you have installed the extension.
> Checkout [installation instruction](https://vspacecode.github.io/docs/) for more details.

Yeah I had some issues in the past and that's what I had done.
Thanks for the reminder to delete it though.

Anyway you're right, it occurs with no relation to vspacecode.
Closing this one, thanks
