### ISSUE TITLE
Python test commands are not found

### ISSUE THREAD

**Issue by Nimamoh** [VSpaceCode/VSpaceCode#247]
In a python project, when launching all tests through default major mode command `m t a`, command is not found

```
Error: command 'python.runtests' not found
```

I suspect command name might have changed since last tested since testing commands in vs studio code seems to follow `testing.<action>` pattern. The issue may be true for other majors mode although I cannot say, just tested with python.

**Comment by stevenguh** [comment]
Related #226. TL;DR: We would like to add the testing to each language/major mode bindings that supports it.

Since vscode has formalized an official testing API, I assume that python extension updated to use the new testing API and command instead.

Would you be able to update our python bindings to have the testing api?
