### ISSUE TITLE
Installing VSpaceCode Plugin For MacOS Doesn't Prompt The User For Automatic Installation Of Default Configurations, Which Results In Spacebar Keybinding Not Actually Working

### ISSUE THREAD

**Issue by SamuelBanya** [VSpaceCode/VSpaceCode#283]
## Bug description
Installing VSpaceCode Plugin For MacOS Doesn't Prompt The User For Automatic Installation Of Default Configurations, Which Results In Spacebar Keybinding Not Actually Working

## To Reproduce
1. Install VSpaceCode plugin for MacOS
2. Doesn't prompt the user to install default configurations as per the 'After the installation of the [VSpaceCode extension](https://marketplace.visualstudio.com/items?itemName=VSpaceCode.vspacecode), a notification will help you to configure both the necessary settings and user bindings.' note on this page:
https://vspacecode.github.io/docs/#manual-configuration-optional
3. This results in the spacebar based Spacemacs style leader key not actually working, which only advances the cursor one character forward.

## Expected behavior
User should be able to observe notification appear on MacOS version of VS Code for VSpaceCode plugin for first time installation.

## Keybindings

<details><summary>Click to toggle contents of `keybindings.json`</summary>
<p>
  
```jsonc
// Copy paste the content of your keybindings.json file here.
```

</p>
</details>

## Settings

<details><summary>Click to toggle contents of `settings.json`</summary>
<p>

```jsonc
// Copy paste the content of your settings.json file here.
```

</p>
</details>

**Comment by stevenguh** [comment]
Yeah, we should update to use the walkthrough API so it's more reliable...

Reference: https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs

**Comment by stevenguh** [comment]
Actually, this may be because you installed VSpaceCode in the past? Possible duplicate of https://github.com/VSpaceCode/VSpaceCode/issues/69

**Comment by mavilar** [comment]
I'm having this same issue in Ubuntu 20.04 LTS.

Since I had it installed previously I tried to remove it completely (including configuration in `~/.vscode` and `~/.config/Code`). After doing that and installing the extension again, it did ask for automatic configuration of keybindings, but the spacebar keybinding still doesn't work.

**Comment by svavs** [comment]
I'm having this same issue in Windows 11 and vscode 1.73.1. 

Don't know if it's related to the MacOs one, because during the first activities it prompts for the automatic installation confirmation, but nothing happens and the spacebar is not showing popups.

After a first install, I tried to remove it completely (including configuration in `C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code` and `C:\Users\<username>\AppData\Roaming\Code`) and installing the extension again: it did ask for automatic configuration of keybindings, but nothing happens. 

I noticed that the spacebar keybinding works only when focusing the sidebar.

So I suppose that in the keybindings.json the following is not working 
```json
{
	"key": "space",
	"command": "vspacecode.space",
	"when": "activeEditorGroupEmpty && focusedView == '' && !whichkeyActive && !inputFocus"
},
```

but this one is working correctly:
```json
{
	"key": "space",
	"command": "vspacecode.space",
	"when": "sideBarFocus && !inputFocus && !whichkeyActive"
},
```

Clicking on the 'space' link in the first activities after installation will correctly prompt the vspacecode.space popup.

There is some easy solution for that?
Thank you for this great extension.

**Comment by stevenguh** [comment]
> Since I had it installed previously I tried to remove it completely (including configuration in `~/.vscode` and `~/.config/Code`). After doing that and installing the extension again, it did ask for automatic configuration of keybindings, but the spacebar keybinding still doesn't work.

We use global state to store if a user is a first time install. That global state is stored in a sqlite data separately and doesn't automatically gets removed on extension uninstallation. Reference: https://mattreduce.com/posts/vscode-global-state/

**Comment by stevenguh** [comment]
> After a first install, I tried to remove it completely (including configuration in `C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code` and `C:\Users\<username>\AppData\Roaming\Code`) and installing the extension again: it did ask for automatic configuration of keybindings, but nothing happens.

hmmm...weird.

> Clicking on the 'space' link in the first activities after installation will correctly prompt the vspacecode.space popup.

This is because that's involving the command directly.

> There is some easy solution for that? Thank you for this great extension.

It seems like you are missing some configuration changes in `settings.json`. Make sure you have all the keybindings and settings as described in the manually installation https://vspacecode.github.io/docs/#manual-configuration-optional

**Comment by svavs** [comment]
> It seems like you are missing some configuration changes in settings.json. Make sure you have all the keybindings and settings as described in the manually installation https://vspacecode.github.io/docs/#manual-configuration-optional

Thank you @stevenguh, I was searching only through the keybindings.json, but the missing part was in the setting.json.

The only line already present in the settings.json was `"vim.useSystemClipboard": true,`, all other required configuration settings was missing.

I still don't know why the automatic configuration don't add the required settings.

Thank you for your help.

**Comment by practicalli-john** [comment]
I had an older version of everything installed.  After updating to VSCode 1.70 and installing VSpaceCode I did not get the automatic configuration window.

Removing `$HOME/.vscode` and `$HOME/.config/Code` directories from my Linux operating system resolved the issue.  The VSpaceCode automatic install page showed, although it failed to update the User configuration files.

The manual commands did update the user configuration files though.  I ran the combined settings and keyboard command and nothing was update.  However running the individual commands did update the user configs

* VSpaceCode: Configure Default Settings and Keybindings (no update to either file)
* VSpaceCode: Configure Default Settings (updated settings.json)
* VSpaceCode: Configure Default Keybindings (updated keybindings.json)

**Comment by stevenguh** [comment]
@practicalli-john Thanks for letting us know. Fixed in #303.

**Comment by stevenguh** [comment]
I manually tested it and t configured both `keybindings.json` and `settings.json`. Have you tried manually call this command?
<img width="612" alt="image" src="https://github.com/VSpaceCode/VSpaceCode/assets/3455662/257172b9-5d2a-4986-8637-eeffc84ce566">

**Comment by SamuelBanya** [comment]
I reinstalled today, and in the home screen, I noticed VS Code prompted me with a greeting screen about 'VSpaceCode'.

I then clicked it, and it then asked if it wanted to reconfigure my keybindings in the corresponding JSON file.

I let it do those actions, and it appears it works just fine on the latest MacOS (MacOS Version Sonoma 14.1.2 with M2 Macbook Pro).

Just wanted to give this update in that I think the latest update fixed this issue. Will close this issue, thanks again, looks like a cool plugin dudes. Spacemacs rules :)
