### ISSUE TITLE
Hide the which-key menu

### ISSUE THREAD

**Issue by Yousuf28** [VSpaceCode/VSpaceCode#367]
Thanks for the extension. I like the key-bindings as I am a doomemacs user. This is very helpful.
Quick question.
Is there any way to hide which-key popup?  or change the location where it is popup? 
I know lot of keybindings, sometime I don't need pop up the which-key suggesions.

Thanks in advance.

**Comment by stevenguh** [comment]
Since we are using the QuickPick API, we need the menu for input handling at the very least.

A couple of alternative:
1. Use the old [vim based](https://github.com/VSpaceCode/VSpaceCode/tree/vscode-vim) branch
2. Set the `whichkey.delay` for a long time enough time to not show the menu.
3. You may able to play with some CSS to tweak this: https://github.com/VSpaceCode/vscode-which-key/issues/37

Marking as close for now as there's much we can do due to API limitation.
