### ISSUE TITLE
Collaboration with vscode-hydra

### ISSUE THREAD

**Issue by pavkum** [VSpaceCode/VSpaceCode#41]
Continuation from #1 regarding collaborating with [vscode-hydra](https://marketplace.visualstudio.com/items?itemName=pavkuml.hydra).

@MarcoIeni @StreakyCobra

As far as I understand, we have different plugins aiming to solve the following problems.

1. Extending shortcut length
 VSCode default shortcut length is 2 chars long and IMO is vastly underpowered for keyboard heavy users
2. which-key sort of support
Aid users with shortcut completion similar to emacs / vim
3. Easy configuration of shortcuts
VSCode has a lot of commands and the list is not maintained anywhere. Everyone many not be comfortable in digging deep to find the required command. 

My proposal involves developing an intermediate interface which maps VSCode commands with semantic-named-commands with the following capabilities

1. Should auto generate keybindings based on the naming convention of semantic-named-commands
2. Should identify focus changing events and handle them appropriately 
3. Provide a semantic language for end-user configuration which maps to semantic-named-commands
4. The usuals: command autocomplete, suggestions etc

Here is an example of default configuration. 
1. `window.terminal.toggle` -> executes vscodes toggle command -> should generate keybinding : `wtt`
2. `window.terminal.toggle:::true` -> invoke terminal toggle command with argument as true -> should generate keybinding `wttt` or ask for configuration if conflict arises. `:::` is the separator for argument
3. `Window.activity.toggle` -> executes vscodes toggle activity bar command -> should generate keybinding `Wat` (notice uppercased W)

The above commands should create the interfaces below
1. window
- terminal
  - toggle
2. Window (uppercase W)
- activity
  - toggle

Assuming that the above commands are default and are provided by us, everyone may not be happy with them. Lets assume someone wants to group them under key `a`

User defined semantic language could be something like this. `$` signifies user namespace.

1. `$application` = `window`
All commands and keybindings of window namespace is mapped to application namespace for key `a`
2. `$application.$terminal` = `window.terminal`
All commands and keybindings of `window.terminal` namespace are mapped to `a.t` namespace
3. `$project.$search` = `#editor.action.find`
Namespace `p.s` is mapped to vscode command `editor.action.find`
.. and so on

Once the interface is developed, we can use it in our respective extension as a command provider.

Let me know your thoughts.

**Comment by MarcoIeni** [comment]
> 1. Extending shortcut length
VSCode default shortcut length is 2 chars long and IMO is vastly underpowered for keyboard heavy users

We register keys by using vim. For example I tried:
```
    "vim.insertModeKeyBindings": [
        {
            "before": [
                "f",
                "a",
                "s",
                "d"
            ],
            "after": [
                "<Esc>"
            ]
        }
    ],
```
and it works.

> Should auto generate keybindings based on the naming convention of semantic-named-commands

I don't think that this works for us. For example we have to map terminal toggle to `SPC '` because that's what spacemacs does.

> Should identify focus changing events and handle them appropriately

This looks like a lot of work ^^'

> Provide a semantic language for end-user configuration which maps to semantic-named-commands

You are talking about abstracting all the VSCode actions to the user by adding a layer on top of it? I don't like this, it's too complex for me. It is easier to look into the VSCode actions directly. But this is just a personal opinion of course.
I am not a javascript developer, so I don't like the idea to develop such a complex plugin, sorry.
I prefer to let vim manage our key bindings.

## which key
What about which-key sort of support? :)
we handle our key bindings with the vim plugin (see the example above).
In your opinion is it feasible to achieve which-key behavior? What I saw in [this](https://github.com/pavkum/vscode-hydra/blob/master/images/hydra-suggestions.gif) gif of vscode-hydra is awesome!

**Comment by MarcoIeni** [comment]
I am closing this, if you have other ideas, please leave a comment
