### ISSUE TITLE
Restore old features

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#52]
As you may noticed this project was merged with [spacecode](https://github.com/stevenguh/spacecode) and some key bindings and settings that existed only in this project are not in the master branch anymore.

The old approach of the repository (before the merge) is maintained in the [vscode-vim](https://github.com/VSpaceCode/VSpaceCode/tree/vscode-vim) branch.

The features that got lost in the process are the following:

- [X] [keybindings.json](https://github.com/VSpaceCode/VSpaceCode/blob/vscode-vim/keybindings.json): easy menu navigation.
- [X] [settings.json](https://github.com/VSpaceCode/VSpaceCode/blob/vscode-vim/settings.json) contains the settigs `"vim.useSystemClipboard": true` and `
    "vim.easymotion": true`.
- [x] [settings.json](https://github.com/VSpaceCode/VSpaceCode/blob/vscode-vim/settings.json) contains all the old key bindings, too. This is why I added the "good first issue" label. You should identify the key bindings of the `settings.json` file that got lost during the process and add them in [this](https://github.com/VSpaceCode/VSpaceCode/blob/7a8b3f4b0d5d3c614e95a67d9b643c97043f3574/package.json#L59) file which contains all the new key bindings. If two key bindings conflict, the most similar to the spacemacs behaviour should win. Try to add few key bindings (also one is ok) for each pull request.

 If there is no way to "install" some parts of `keybindings.json` or `settings.json` with the plugin (i.e. set the key value pair as default when this plugin is installed), a new `settings.json` file that contains all these parts should be created and the README should explain that it requires to be manually merged in your own `settings.json`.
At the moment it is acceptable that some key bindings that cannot be integrated with the plugin are included only in the new `settings.json` file and therefore are not listed in the which-key window.

**Comment by stevenguh** [comment]
I just want to give a little bit more context before more work is being done on it.
In the upcoming `v0.4.0` update,
- The majority of the binding will be "restored"
- Any commands with `<tab>` cannot be used/restored in the "which-key menu" currently without any hacky workaround
- A `bonus` section of a quick window nav that I used in the README
   (@MarcoIeni Can you tell me does the old easy menu navigation do?)
- easymotion keys are currently not present in the upcoming `v0.4.0` (but it's possible only after `v0.4.0` as in user can add in manually via overrides for now) because the extension currently have prompts to help user to do the initial setup. However, the prompts currently doesn't check those settings yet. Additional, I am consider removing the settings check feature.

**Comment by stevenguh** [comment]
I think the old window navigation can also be put into the `Bonus` section of README in `v0.4.0` and make the Bonus section collapsible

**Comment by MarcoIeni** [comment]
So in order to not create conflicts, new pull requests should ALWAYS be done against the develop branch right? If so we should make it clear in [CONTRIBUTING.md](https://github.com/VSpaceCode/VSpaceCode/blob/master/CONTRIBUTING.md) and in a pull request template.

> Any commands with <tab> cannot be used/restored in the "which-key menu" currently without any hacky workaround

As I said those key bindings which are not compatible with the which-key mechanism should be active, even if they are not listed in which key. They could in the new `settings.json` file that I described before, i.e. a smaller version of the current one, that contains only the key bindings and settings that cannot be handled by the which key mechanism.
Anyway maybe we have better alternatives that creating a settings.json to be merged manually:
1. I saw that we are able to append stuff in the settings.json file, so we could add the old non compatible key bindings to the settings.json of the user
2. We could silently activate these key bindings in our plugin and list them somewhere in the docs. So the behavior is the same as if they were in the user settings.json, but they are not there, so user is not annoyed. (I prefer this option if it is feasible)

> @MarcoIeni Can you tell me does the old easy menu navigation do?)

I explained it wrong, you have to copy paste the content of the keybindings.json in your keybindings.json and they let you navigate in menu with ctrl+{h,j,k,l}. ctrl+j and ctrl+k work even in the which-key plugin.
You cannot copy them in the settings.json file.
As before, could we activate this by default or copy paste is required by the user?

> Additional, I am consider removing the settings check feature.

Yes, that prompt is a little bit confusing..I think we should set a default behavior and in the README we explain how to change it for the 1% of users interested.

**Comment by stevenguh** [comment]
> So in order to not create conflicts, new pull requests should ALWAYS be done against the develop branch right? If so we should make it clear in CONTRIBUTING.md and in a pull request template.

I haven't figured out the exact flow yet, but that's what I am thinking because partly because I didn't want github to display unreleased README page. Thinking keeping a mostly linear git history by using rebase and squash if needed.

> I explained it wrong, you have to copy paste the content of the keybindings.json in your keybindings.json and they let you navigate in menu with ctrl+{h,j,k,l}. ctrl+j and ctrl+k work even in the which-key plugin.

I think this is really a "bonus" feature that if people want to config that behavior they could. That's why I added a Bonus section in the README in the develop branch release on Monday to contains other "bonus" configuration. I am thinking copy and paste is required for these.

> Yes, that prompt is a little bit confusing..I think we should set a default behavior and in the README we explain how to change it for the 1% of users interested.

for the 1% of users interested? Not sure if I understand completely. My thinking on this is that there's going to be something that we can't automate well in all cases like `keybindings.json` (e.g. support `y` menu like spacemacs for edamagit) or in VSCode Remote environment. It is my current thinking to remove the whole initial setup in favor of some manually initial setup by the users, possibility in `v0.5.0` since the support of `y` menu in edamagit is part of the goal.

> As I said those key bindings which are not compatible with the which-key mechanism should be active, even if they are not listed in which key. They could in the new `settings.json` file that I described before, i.e. a smaller version of the current one, that contains only the key bindings and settings that cannot be handled by the which key mechanism.

After the release of release of `v0.4.0`, most of the bindings should be restored. For those that technically can't be restored like `<TAB>` or modifier keys, I don't *think* the pre-merged `settings.json` can be used to replicate bindings like `<spc> <tab>` for example. Because the `<spc>` key is bond to execute a command in spacecode, I assumed that `<spc>` can not be used as leader key vim. Since most of the keys in the `settings.json` setup as default settings of `vspacecode.bindings`, the rest of settings in pre-merged `settings.json` are things like system clipboard and easymontion.

> Anyway maybe we have better alternatives that creating a settings.json to be merged manually:
> 1. I saw that we are able to append stuff in the settings.json file, so we could add the old non compatible key bindings to the settings.json of the user

The settings check is currently doing something similar what you described in 1. However, there are quite some edge cases that make it kind of clunky. I am thinking to gut out the automatically checking in the future. I am also thinking we can keep the checking and installation as a command that people can do with `Ctl+shift+P`. However, that still doesn't solve the existing problems with vscode remote and additional bindings.

> 2. We could silently activate these key bindings in our plugin and list them somewhere in the docs. So the behavior is the same as if they were in the user settings.json, but they are not there, so user is not annoyed. (I prefer this option if it is feasible)

It depends how silent the part works, we may not able to provide an escape hatch for people. Or like similar like a command thing, however, it still has the problems mentioned.

---
Overall,
- Needs to update with CONTRIBUTING.md
- Favoring manual installation for now until a better automating solution exists
- The surface of the rest of the settings.json should be small after `v0.4.0` that we can explain in README.md
- Key bindings that uses `<tab>` or modifiers may not be restored (explain in README?)
- The pre-merged keybindings are like the bonus section in the README (optional config for people)

**Comment by MarcoIeni** [comment]
> That's why I added a Bonus section in the README in the develop branch release on Monday to contains other "bonus" configuration. I am thinking copy and paste is required for these.

Ok, so we have to bring the file keybindings.json in the develop branch, copy the instructions on how to use it from the old README and place them in the "Bonus" section.

> for the 1% of users interested? Not sure if I understand completely. 

I thought that since 99% of the user will just accept the automatic installation this should be the default, but I am not sure what automatic installation is doing, but you know that part better than me of course, so just ignore me on this :)

> the settings that left in settings.json are things like enabling system clipboard and easymontion, and some missing bindings like <spc> j

> there are quite some edge cases that make it kind of clunky.

Ok, so for now we might do the same things of keybindings.json, i.e. we provide a settings.json file and in the README we say to merge its content into user's one?
The settings.json file content should be the following:

```json
{
    "vim.easymotion": true,
    "vim.useSystemClipboard": true
}
```

> Key bindings that uses <tab> or modifiers may not be restored (explain in README?)

- [ ] Maybe we could add a "Limitations" section.

> they will need to enable easymontion for vim.

- [ ] We will mention it in the installation instructions.

Anyway, if you agree I will do the actions I described before for keybindings.json and settings.json.

**Comment by stevenguh** [comment]
> Ok, so we have to bring the file keybindings.json in the develop branch, copy the instructions on how to use it from the old README and place them in the "Bonus" section.

Not necessary the file, but just the content of old `keybindings.json` to the Bonus section of the readme and explain what those do, because I put in the quick window navigation I used in that section that might in conflict with the old `keybindings.json`. If that section gets big, we can always use a collapsible section or move to a a wiki page?

> I thought that since 99% of the user will just accept the automatic installation this should be the default, but I am not sure what automatic installation is doing, but you know that part better than me of course, so just ignore me on this :)

That may be true, in that case, we just have to work out the edge cases. I am still thinking rolling back feature in `v0.5.0` if we can't automate well enough. (per below, needs more time to figure this out)

> ```
> {
>     "vim.easymotion": true,
>     "vim.useSystemClipboard": true
> }
> ```
Strictly speaking these aren't needed for `v0.4.0` but they are needed for when we add `<spc> j` in the future. Because I chose to support non-vim in the beginning (not sure how many people are non-vim users), this makes the whole thing very complicated, and I am planned to spin out of the `vscode-which-key` in `v0.5.0` so this extension can focus on `vim` only. Needs more time to thinking about how should we handle installation still. Meanwhile, we can add those into the Vim section of the README as optional/recommended settings?

> Maybe we could add a "Limitations" section.

Yes 😊

> We will mention it in the installation instructions.

Also yes when we have a `<spc> j` which we don't just yet in the `v0.4.0`.

**Comment by stevenguh** [comment]
Opened #57 to track installation work and discussion.

**Comment by MarcoIeni** [comment]
> Not necessary the file, but just the content of old keybindings.json to the Bonus section of the readme and explain what those do

Ok, I noticed that you didn't include all the content of the keybindings.json file. Why?

> Meanwhile, we can add those into the Vim section of the README as optional/recommended settings?

I have done it in c26ce3f . We will add `"vim.easymotion": true` when our key bindings will use it (we aren't able to set it automatically, right?)

**Comment by stevenguh** [comment]
> Ok, I noticed that you didn't include all the content of the keybindings.json file. Why?

That's no particular reason. I thought you are going to add it. Thank you for the follow up. I added it to the README in https://github.com/VSpaceCode/VSpaceCode/commit/2607ea4b15dd9f96e2b81c91335e6354555b39ba. However, I don't think I explain it very well. Feel free to make it more descriptive as I am not too familiar with what that does.

> I have done it in c26ce3f . We will add "vim.easymotion": true when our key bindings will use it (we aren't able to set it automatically, right?)

We can update settings as part of an installation process, but I am still in the process of recoding that part, so collaborator can easily add default settings as part of installation easily. Once I am done with that I will add `vim.easymotion` as part of the effort to add `<spc> j` menu

**Comment by stevenguh** [comment]
I am wondering what else is needed to close out this issue?

**Comment by MarcoIeni** [comment]
I will do a check in late July to check if something is missing. Sorry, but I am a little bit busy at the moment :/
I will assign this issue to me and I will remove the "good first issue" label in order to make it clear that this issue does not require a lot of attention until I will update it.
Anyway if someone finds an old feature that's missing, fell free to comment here.

**Comment by stevenguh** [comment]
Just open an issue to track the work you mentioned at the very beginning to automatically merge easy menu navigation to user's `keybindings.json` now that we have the ability to automatically configure user's `keybindings.json` #66

**Comment by MarcoIeni** [comment]
I marked `keybindings.json` as done since I merged almost all the differences in 9baa9f31dd5197115440 and 3f73039d8001e9e7421e0e6f285b362e8936cf46.

The only difference left is the `when` of these key bindings:
https://github.com/VSpaceCode/VSpaceCode/blob/39fda773007f3b78bc2035a3fbc932ce99ca0c6d/src/keybindings.jsonc#L89-L98

against these ones:
https://github.com/VSpaceCode/VSpaceCode/blob/010dddc2498cc38ac4da9792426d4f349494f19e/keybindings.json#L12-L21

but I don't know if one version is better than the other one. So I will leave things as they are. It would be nice if someone spots the difference and says which version is the most convenient.

**Comment by stevenguh** [comment]
Thank you for working through the issue. The reasons I put those bindings in 9baa9f3 and 3f73039 in the [README extra section](https://github.com/VSpaceCode/VSpaceCode#easy-list-navigation) instead of `keybindings.jsonc`  because
1. Vim already binds `h/j/k/l` for list including file explorer
2. Neotree in spacemacs doesn't bind `Ctrl+h/j/k/l` for navigation
3. Those `ctrl+h/j/k/l` list traverse will break "Quick Window Navigation" in README

That's why I put those in README instead of in the keybinding command. Let me know what you think.

For the `when` issue, I used the one in the default `when` for the built-in shootouts for `selectNextSuggestion` and `selectPrevSuggestion`. I am not sure where the old one was coming from.

**Comment by MarcoIeni** [comment]
I completely missed the fact that those key bindings were already present in the README. ^^'

Anyway I see only benefits in adding those key bindings by default:
1. they continue to work
2. Most of the times I use vscode file explorer as if it was helm, not neotree, so I am used to those key bindings
3. We could specify to replace these key bindings with the "Quick Window Navigation" ones

If for you is ok, I will edit the README.

**Comment by stevenguh** [comment]
My thoughts are either:

- edit the `README` to mention to take those out if a user want to use "Quick Window Navigation"

or 

- specific the `when` for those commands so it has a narrow scope like specifically for file explorer

**Comment by MarcoIeni** [comment]
Both are ok for me, but the downside of the second option is that the "problem" tab will stop working as you mentioned in the readme.
Maybe the best solution would be to edit the `README` in order to edit the `when`, instead of completely removing them. So they could coexist.

**Comment by stevenguh** [comment]
> Both are ok for me, but the downside of the second option is that the "problem" tab will stop working as you mentioned in the readme.
True. I guess the root of the problem is automatic vs manual. Both are okay as well as they are well documented in both CHANGELOG and README I guess.

> Maybe the best solution would be to edit the README in order to edit the when, instead of completely removing them. So they could coexist.

I am not sure if I understand this what this solution entails?

**Comment by MarcoIeni** [comment]
> I am not sure if I understand this what this solution entails?

Sure!

With respect to the first option you described (edit the `README`), instead of mentioning to taking out those key bindings, we say to edit the `when` to reduce the scope for file explorer.

It's like a merge of the two options. Tell me if it's clear now :)

**Comment by stevenguh** [comment]
I would mention to take those out completely, cause I think even reducing the scope would still have some other issues. Ca you mention that in both README and CHANGELOG? Thanks :)

**Comment by MarcoIeni** [comment]
Yes, I'll try to do it tomorrow

**Comment by MarcoIeni** [comment]
> I would mention to take those out completely, cause I think even reducing the scope would still have some other issues. Ca you mention that in both README and CHANGELOG? Thanks :)

Done in 88ff6c8824380de2062351a0521538ebe55da4c3

**Comment by MarcoIeni** [comment]
I reviewed all the key bindings, too. Some of them were ignored, some merged and for `<spc> w m` I created #77

**Comment by stevenguh** [comment]
@MarcoIeni I am thinking to revert the changes of the automatic setup of `ctrl+h/j/k/l` for file explorer and it will still be described as extra in README. Those bindings are too board and make future keybindings that might use `ctrl+h/j/k/l` more difficult. Especially when there's a conflict, although, we should figure out a better upgrade staggery to keybindings.

**Comment by MarcoIeni** [comment]
Yes, sure

**Comment by stevenguh** [comment]
Thanks, will release a new version with your changes later today :)
