### ISSUE TITLE
Delay before showing menu

### ISSUE THREAD

**Issue by davidmauskop** [VSpaceCode/VSpaceCode#55]
It would be awesome if the extension gave the option of adding a delay before the quick pick menu appeared (like in spacemacs). I realize this may be hard to implement since the extension currently relies on the quick pick to capture input, but thanks for considering it.

P.S. Many thanks for this extension. I recently switched from spacemacs to VS Code and this extension makes my VS Code experience so much better.

**Comment by stevenguh** [comment]
Like you said, it is currently relying on quick pick api for the input, so not sure how this could be achieved. But will keep this open.
Btw, I am glad you like it :)

**Comment by MarcoIeni** [comment]
Today I tried the extension inside virtualbox with an i5 2018 laptop. 
If you type really fast the key bindings are not read correctly. For example if you type `<SPC>wh` (really fast) the plugin reads `<SPC>w` only.

Introducing a delay may solve this. A temporary solution I am using is to use the [vscode-vim](https://github.com/VSpaceCode/VSpaceCode/tree/vscode-vim) branch in this situations.
Anyway, VSCodeVim is pretty slow too.

**Comment by stevenguh** [comment]
I thought about this a little bit more, this is possible. We can present an empty quick pick and display menu items with a delay. If the assumption of the slowness is mostly attributed to the rendering of the menu items, I believe this could help. In any way, this is probably a good additional feature to have.

Since we are moving the core of the menu structure to [vscode-which-key](https://github.com/VSpaceCode/vscode-which-key), I will tag this with `which-key` to indicate this is an issue related which-key menu code and should be work on the that repo.

I excepted this work item will be worked on after `v0.5.0`, which will bundled "vscode-which-key" extension on installation time, and currently low priority on my list, especially it does require some refactoring of the core menu.

**Comment by stevenguh** [comment]
Released `v0.6.0` of vscode-which-key which contains this feature. Set `whichkey.delay` in your `settings.json` to the delay of the menu display in milliseconds.

**Comment by davidmauskop** [comment]
Thank you! 🙏
