### ISSUE TITLE
Evaluate vscode-file-browser

### ISSUE THREAD

**Issue by codeincontext** [VSpaceCode/VSpaceCode#65]
Thanks for your work on this so far, the new version is great.

This plugin seems like a really good emulation of Helm. Maybe it could replace `space f f`?

https://github.com/bodil/vscode-file-browser [edit: fixed link]

**Comment by stevenguh** [comment]
There are some missing features like tab completion, folder opening, vscode remote support. Otherwise, this seems very promising. Maybe we should open some issues in that repo to if he has plan to support them?

btw, the link you have is missing a r at the end
https://github.com/bodil/vscode-file-browser

**Comment by codeincontext** [comment]
> There are some missing features like tab completion, folder opening, vscode remote support. Otherwise, this seems very promising. Maybe we should open some issues in that repo to if he has plan to support them?

I know you're not a native English speaker, but by the way the author is a woman.

I'm happy to open an issue with your suggestions and see what she says

> 
> btw, the link you have is missing a r at the end
> [bodil/vscode-file-browser](https://github.com/bodil/vscode-file-browser)

Ah, you're right. Apologies

**Comment by stevenguh** [comment]
I am so sorry. It would be great to start a conversation, and thank you for driving the effort.

The other issue I can see is that, the library is using LGPL-3 license. Would putting that in our extension pack changed this repo license? Since this library is not embedding the binaries, and the extension installation is handle by vscode, would that be okay?

**Comment by codeincontext** [comment]
I just created an issue at https://github.com/bodil/vscode-file-browser/issues/2

**Comment by stevenguh** [comment]
Thank you @codeincontext

**Comment by stevenguh** [comment]
Remove this from `v0.6.0`, and I think the author of `vscode-file-browser` is working on fixing vscode remote.

**Comment by stevenguh** [comment]
Released `v0.7.0` that bundles `vscode-file-browser` to fix #73 without introducing command specific for different platform. There are two known issues listed in README related to vscode remote; however, those issues are small enough to ship it to fix #73.

- File browser (bound to<spc> f f) doesn't work correctly when the active document is a local file with VScode Remote
- File browser (bound to <spc> f f) doesn't have a button to open local file with VSCode Remote

**Comment by codeincontext** [comment]
🙌 great work!

**Comment by stevenguh** [comment]
Thanks for leading the effort
