### ISSUE TITLE
Find a key binding to toggle bottom panel

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#81]
The action "workbench.action.togglePanel" is really nice. Do you have any ideas about which key binding to assign?

**Comment by MarcoIeni** [comment]
"workbench.action.focusPanel", too

**Comment by stevenguh** [comment]
Maybe we can bind a shortcut to defocus instead having a key binding in the which key menu? I am thinking like helm where the bottom panel can be dismissed by `esc`; however, terminal view and other view might need to capture `esc`. I am not sure.

**Comment by MarcoIeni** [comment]
- The action "workbench.action.togglePanel" makes the panel happear/disappear.
- "workbench.action.focusPanel" let you focus on the panel.
- What you are proposing let you defocus from the panel. So it's complementary. This could be a separate issue, since the problem is different.

**Comment by stevenguh** [comment]
Sorry, I guess I didn't articulate my thoughts well. I was thinking if we have #85 then `<spc> w j` should be able focus the panel using `workbench.action.navigateDown` without explicit command to `workbench.action.focusPanel`. This is definitely just complementary to this issue.
 
I actually added a key binding with `<spc> T j` to toggle panel a while back because `cmd+j` is the shortcut to toggle panels. We can definitely change it if that doesn't make sense.

**Comment by MarcoIeni** [comment]
> I actually added a key binding with `<spc> T j` to toggle panel a while back because `cmd+j` is the shortcut to toggle panels.

completely missed that, sorry :/

> I was thinking if we have #85 then `<spc> w j` should be able focus the panel using `workbench.action.navigateDown` without explicit command to `workbench.action.focusPanel`.

I added a [comment](https://github.com/VSpaceCode/VSpaceCode/issues/85#issuecomment-673324781) in that issue.

I close this since I think nothing is remaining.
