### ISSUE TITLE
Implement missing "yank/copy path" related commands

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#83]
In spacemacs (develop branch) there are a lot of key bindings under `<spc> f y` that are missing in VSpaceCode.

Some related to file path:
- [x] `<spc> f y c` copies file path with line and column numbers, for example: `/home/marco/VSpaceCode/CHANGELOG.md:39:15`
- [x] `<spc> f y d` copies the directory path, for example: `/home/marco/VSpaceCode/`
- [x] `<spc> f y l` copies file path with line number, for example: `/home/marco/VSpaceCode/CHANGELOG.md:39`

The above key bindings have a version where instead of the absolute path, you refer to the project root, in my case `/home/marco/VSpaceCode/`
- [x] `<spc> f y C` copies file path with line and column, for example: `CHANGELOG.md:39:15`
- [x] `<spc> f y D` copies directory path, for example: `./`
- [x] `<spc> f y L` copies file path with line number, for example: `CHANGELOG.md:39`

plus, you have:
- [x] `<spc> f y n` copies file name, for example: `CHANGELOG.md`
- [x] `<spc> f y N` copies file name without extension, for example: `CHANGELOG`

## implementation

Here is an example implementation: https://marketplace.visualstudio.com/items?itemName=ezforo.copy-relative-path-and-line-numbers

Anyway there is no linked repository, so maybe it's not open source. Plus, stevenguh [here](https://github.com/VSpaceCode/VSpaceCode/commit/5c540149122e2c77a50d69e04d927ea7e6cc61d1#commitcomment-41320640) said that using a lot of external extensions comes with an overhead, so we might want to implement and maintain those little actions in this extension.
These look simple to me, so I will add the good first issue label. Write here if you want to implement one of those actions :)

**Comment by stevenguh** [comment]
Here are the APIs we are likely to use:
- `window.activeTextEditor?.document` to access file path, line number, and column
- `env.clipboard.writeText` to write clipboard.
- `window.setStatusBarMessage` to display to copied text

**Comment by stevenguh** [comment]
These are all implemented on the `yank` branch. However, one issue reminds is that the path copied use the host machine's separator on vscode-remote. For example, using vscode-remote to connect a window machine (host) to a *nix machine will return path like "\some\path" which is not ideal.

Since VSCode API doesn't really provide mechanism to resolve path separator issue AFAIK.

There are two solutions:
1. Somehow figure out what the remote platform is base on the uri like regex.
2. Separates those path functions into another extensions that we bundles. This works because the extension will run native on the remote platform and will have the right path separator by default.

I am incline to try the second option, because it doesn't assume what pattern of the string is a window/*nix path. One question I have is what should the name of the package be? `vscode-copy-path`?

**Comment by MarcoIeni** [comment]
> the path copied use the host machine's separator on vscode-remote

What if we open an issue in the [vscode repo](https://github.com/microsoft/vscode) about this?

**Comment by stevenguh** [comment]
Lots of source code digging in vscode 😅 I figured out a way do it without another extension that is pretty much just like how they are handling it internally. This is really a case of some early assumptions in the vscode API working against their added feature in this case vscode-remote. You mentioned earlier to open an issue in vscode, I am not sure if I should since they have sooooo many issues in their repo😅

Yay for not needing to bundle another extension, and able to handle without install extension locally (on the remote) with vscode-remote. We can always fallback to bundling another extension, but I am happy with where I ended up.

This should be ready. I tested on multiple variations of local and remote platform, and they all have the right path separator. 

The following are the test cases:
- Copy absolute/relative path of a local file with a single folder workspace in local machine on Mac
- Copy absolute/relative path of a local file in location with drive letter path (`C:\path\to\file`) with a single folder workspace in local machine on Windows
- Copy absolute/relative path of a file in location with UNC path (network drive like `\\wsl$\Ubuntu\abc`) with a single folder workspace in local machine on Windows
- Copy absolute/relative path of remote file (on Windows) with a single folder workspace in a vscode-remote instance (Remoting from Mac to Windows) 
- Copy absolute/relative path of local file (on Mac) with a single folder workspace in a vscode-remote instance (Remoting from Mac to Windows)
- Copy absolute/relative path of a remote file (on Linux) with a single folder workspace in a vscode-remote instance (Remoting from Windows to Linux)
- Copy absolute/relative path of a local file (on Windows) with a single folder workspace in a vscode-remote instance (Remoting from Windows to Linux)
- Copy absolute/relative path of a remote file (on Linux) named `\` in a folder under the workspace folder named `\` with a single folder workspace in a vscode-remote instance (Remoting from Windows to Linux)
- Copy absolute/relative path with multiple folder workspace in local machine on Mac

**Comment by stevenguh** [comment]
Close as it is merged to develop, and will release a minor version later today.

**Comment by MarcoIeni** [comment]
> You mentioned earlier to open an issue in vscode, I am not sure if I should since they have sooooo many issues in their repo

if you think it could improve the project I think you should :)

**Comment by stevenguh** [comment]
Commented on a related issue on vscode https://github.com/microsoft/vscode/issues/82739#issuecomment-683330593
